### ISSUE TITLE
Proposed Story

### ISSUE THREAD

**Issue by aawadall** [aawadall/Game-Off-2018#2]
This idea was proposed by my son: 

> Micky mouse club house but mash up with fairy tales or movies, like boss fights and all of that

**Comment by Fredster64** [comment]
Both ideas sound interesting - but I'd be worried about licensing and stuff. Also, it sounds like these games would involve the creation of a lot of art etc which would probably take a lot of time. 

I was thinking of something a bit more simple, like a 2D puzzle-platformer - at the start of each level, you'd pick two characters to play as, and then in the level you'd play as a hybrid of those two characters with some traits from each. 

Alternatively, if you think you could make it work (I'm not good with AI so I wouldn't be much help with the mechanics), I was thinking of a game where the player controls one head of a multi-headed monster, with each head having different objectives they want to satisfy - the aim is to get the heads to agree on moving the body so that your mission is completed before those of any of the other heads (if that makes sense). 

Great ideas all round though! :)

**Comment by aawadall** [comment]
@Fredster64 so let me paraphrase your ideas:

- [ ] idea 1 - **Pokemon monster style mashup** 
- [ ] idea 2 - **single agent controlled by multiple users** to reach one final goal? is it like one user controls the steering wheel while the other user controls accelerator/breaks of a truck?

**Comment by Fredster64** [comment]
@aawadall  Kind of: 

1) pretty much - but the main idea is that the player gets to choose which two monsters/animals to fuse together in order to complete a given level: e.g. if there was a level with big gaps in the floor, they might choose a bird and a kangaroo (or something) so that their hybrid can fly and jump high. 

2) this would be one way of making the game, although I was thinking more of a cerberus-type thing. The heads in this idea would have opposing aims and the whole creature can only do something if the majority of the heads agree that it would help them complete their own aims. Hope I explained that well enough!

**Comment by aawadall** [comment]
@Fredster64  for proposal 1, this can follow the rules below
1. Start with a list of basic monsters/animals/agents 👹 
1. each agent will have a collection of traits, defined in a vector, e.g. speed = 0.123, durability = 0.99, strength = 0.01, intelligence = - 0.24, etc. 
1. when blend/breed a new agent, we can randomly pick traits from each parent 👪  (and maybe add some random mutation), and come up with a _hybrid_ child 👶 
1. this child is added to the agents list 
1. each basic agent and child in the list above can compete with another opponent from the same list on one or more tasks

sounds great 👍  

It can be a simple 2D type of plan and simulate game

**Comment by Fredster64** [comment]
Sounds good! :) I worry that the game might be a bit easy if the tasks are entirely simulated though - maybe the player should still have to do some platforming/fighting?

**Comment by yxng-zayd** [comment]
I was thinking i could go with the free roam game and we can look for ppl
who are willing to do art work other than me. I was also thinking i could
ask some of my classmates for participating in this game off too

**Comment by yxng-zayd** [comment]
And also that i a great idea

**Comment by aawadall** [comment]
@yxng-zayd so a sand-box game with monsters bred from randomly generated parents?
what sort of tasks they perform?
- [ ] Fight?
- [ ] Race?
- [ ] Solve Problems? Pass Maze?

**Comment by Fredster64** [comment]
Personally, I really like the idea of different monsters using their individual skills to solve puzzles (perhaps with some combat along the way).
However, I do think that having randomly-generated parents would complicate the game quite a bit (most notably from an art design point of view), and I also think that the game would be more satisfying to play if  the player starts with a fixed roster of parents to fuse/blend/whatever.

**Comment by aawadall** [comment]
Random parents shouldn't be that complicated, I would think of a parent to be an object made of the following attributes:
- Name 
- Picture(s)/Sprites
- Traits/Powers 
- Behaviors 

We can create a factory method randomly drawing names, sprites and powers from a global list with no replacement. 

when two monsters breed, we use a different factory method, to draw names and sprites at random from the global list, but powers would be selected at random from both parents. 

as for behavior, it should be a function of powers, e.g. flying will be a function of flying power, if flying = 0 then it cannot fly, and if it has a small value, say 0.01, then it can jump only

**Comment by Fredster64** [comment]
@aawadall Sounds like a good way of doing it - I'm sold! 

I like the idea of harsh environments as well - it would definitely be something I'd want to look into once we've nailed the core aspects of the game. Not too sure what you mean by the game taking place in a lab - is it that the scientist creates the creatures in the lab and then exposes them to the outside world to do his bidding (a thought that I really like - you could have other similar mad scientists to fight against)?

**Comment by aawadall** [comment]
@Fredster64  nice idea, having scientist vs. scientist idea, so back to the Pokemon idea

**Comment by aawadall** [comment]
Let us have powers defined as weights instead of absolute values, so each power would be a percentage of the overall energy of this creature. energy can be defined by the amount of food it consumes, and is limited by some global factor.

and given powers we get behaviors that can be defined as actions in AI language, we can use reinforcement learning for these creatures to interact with the environment (simulator)

that being said, we need to define a simulator with its rules

**Comment by Fredster64** [comment]
So, we need a simulator to determine how the creatures interact with the environment? Sounds good to me. 

I think now would be a good time to try and get a really concrete picture of what the game will be, just so we're all on the same page. Here's what I'm picturing thus far: 

- player controls a mad scientist from a lab, which produces hybrid monsters by a breeding/fusion process. Each of these monsters have different attributes to compete certain tasks in the environment.
 
- tasks involve: 
  - the killing of rival monsters and the protection of your lab; 
  - the building of towers and walls to protect your lab (maybe?);
  - the sourcing of food from the environment, which is used to power up your monsters. Getting this food could be where we use skills like 'flying ability', e.g. getting food from a high tree.

- the overall aim is to defeat the other mad scientists (possibly). 

This sounds like a game I would play! A real-time strategy title with a unique monster-generation method to keep it interesting. If we wanted, we could work some minigames into it as well in keeping with the 'hybrid theme' (e.g. if a monster is collecting food from a tree, it might open up a platforming minigame where they have to climb the tree in a given timeframe)?

**Comment by aawadall** [comment]
@Fredster64  I had a quick meeting yesterday with my children, and they came up with the following theme (which is almost the same as yours)
### the HUB
- Game setting inside a lab, they called it the _HUB_
- a HUB has the following corners/rooms:
    - the _Incubator_: where you make your breeding experiments
    - your _e-Banking Page_: where you track your funds, and maybe ask for loans
    - your _inventory_ or _pantry_: where you store purchased and collected items
    - the _e-Market_: where you buy and sell items
    - _Comms_: where you dispatch your monsters to perform tasks; this leads to playable missions 
    - _HAB_: where you keep your live monsters, plant food, and feed monsters
    - _Research Files_: where you keep monster and plant DNAs and a profile of each monster/plant 

### Game Dynamics 
You start the game with a basic lab, with basic equipment and basic DNAs to start with.
You use the _Incubator_ to breed monsters and plants from parent DNAs and some external factors (as supported by the incubator)
Each monster/plant offspring is a hybrid of both parents plus some random mutation as per your incubator equipment.
Each monster/plant has traits defined by their DNA as percentage of their total energy, e.g. you might have a monster with 3% for flying, 15% for strength, 9% for intelligence, 32% for agility, and so on, and the remaining would be towards inefficiency. final traits would be the product of those weights and total creature energy, which in case of monsters would be food yield, and in case of plants would be light, and soil quality.
you use your plants in the HAB garden to grow food for your monsters, you feed your monsters, then using the comms, you dispatch monsters to perform some tasks, each task yields some money, towards your e-banking, which can be used to buy lab upgrades, DNAs, food, or even pay for utilities 

we were thinking of the name _Monster Nursery_ as a name.

**Comment by Fredster64** [comment]
@aawadall it's good that we're on the same page! 

I think it would be cool to add some kind of observation tower or something in the lab so that you can actually see how your monsters are doing in the real world. Maybe we could have something like: 

- you go to the Comms place and decide to send a monster on a certain mission, e.g. collecting food. 
- then you go to the observatory and decide where you want the monster to gather food from (e.g. you might choose a fruit tree or a herd of wild fodder). 

The game could still take place in the lab, but it would feel like you're interacting with the outside world a bit more.

**Comment by Fredster64** [comment]
What's the objective of the game? Is it to raise a horde of fighting monsters to dethrone your scientific competition? Or should it be more open-ended, like completing the monster encyclopedia, or just trying to raise enough money to fund your research?

**Comment by Fredster64** [comment]
Okay cool, fair enough - makes sense to put the gameplay first. We've definitely got enough to be working on as it is! 

I feel like we're ready to start making the game if everyone else agrees? We should delegate roles and focus on getting the core mechanics in place.

**Comment by aawadall** [comment]
Great, feel free to update the story under docs
in case further discussion is required, we can head to the [slack channel](https://monstersnursery.slack.com/messages/CDWGWN5ML/) 
I will be closing this phase now
