### ISSUE TITLE
Selecting Technology Stack 

### ISSUE THREAD

**Issue by aawadall** [aawadall/Game-Off-2018#3]
By the time we're done with our story, we need to plan for development.
What technology stack should we use in terms of 
* Console application/web application/cross platform
* what language(s) C#, Lua, C++, Python, JavaScript, etc?
* What layout should the game be at? 2D, 3D, Text, ??

**Comment by Fredster64** [comment]
I'd be far more comfortable using Unity with C# than anything else, if that's okay :) I would be up for learning a new technology, but I probably wouldn't be very useful with it! 

Regarding game layout, I think a 2D game would be a lot more manageable from both a level design and art creation point of view, especially given the time constraints we have.

**Comment by aawadall** [comment]
can we export a unity game to the web?

**Comment by Fredster64** [comment]
You can export it to WebGL which I imagine should be okay (sorry, I'm not too good with web technologies)!

The GameOff rules say that we only need to submit a link to the GitHub repository. That said, it would probably be a good idea to include some web builds in the repository so that people can play the game.

**Comment by aawadall** [comment]
C# + Unity
